---
- name: dpeloy application service 
  hosts: all
  become: yes
  gather_facts: true
  vars:
    registry_default: "docker.io"
  tasks: 
    - name: "Login to Docker registry {{ registry_url }}"
      docker_login:
        registry_url: "{{ registry_url }}"
        username: "{{ registry_username }}"
        password: "{{ registry_password }}"
      when: registry_url != registry_default

    - name: "Pull docker image {{ image_full }}"
      docker_image:
        name: "{{ image_full }}"
        source: pull
      
    - name: "Run container {{ container_name }} "
      docker_container:
        name: "{{ container_name }}"
        image: "{{ image_full }}"
        state: started
        restart_policy: always
        recreate: true
        ports:
          - "{{ port_out }}:{{ port_expose}}"